### ISSUE TITLE
Package the Otherapp  WITH file?

### ISSUE THREAD

**Issue by weirdal3333** [nedwill/soundhax#56]
Since this has to do with JUST the metadata, would it be possible to make the 3DS reference the mp4 file instead of the otherapp.bin? If you could find some way to include that in the mp4 file, lots of people would be happy!

Also, can there be a short sound clip if it doesn't work on your version? So you can use it with streetpass?

**Comment by JessterP** [comment]
Seeing as sound hax works with multiple versions and other app doesn't.. this would be more of an annoyance for the developer than its worth cause they would have to create a mp4a for every comparable version...

**Comment by weirdal3333** [comment]
I don't know if this has ever been answered, but why do you need an Otherapp for each system menu version? Couldn't there be some way to just send the payload without a version check?

**Comment by yellows8** [comment]
No, different Home Menu title-versions...

**Comment by weirdal3333** [comment]
After this is polished a little more, I think it would be cool to make it self sufficient and transferrable with streetpass. 
It just needs to be playable and have an Otherapp payload built it. You can have up to 5 tracks in the streetpass playlist.

Also, is there a link that caches/downloads the boot.3dsx file somewhere?

**Comment by Mrremrem** [comment]
By that do you mean download the boot.3dsx file itself? If so, then the link for that is here[](http://smealum.github.io/3ds/) . It is under the 'Preparing your SD card' section.

**Comment by yellows8** [comment]
FWIW it doesn't actually send any {sound-file-from-SD} with StreetPass AFAIK....

**Comment by nedwill** [comment]
I definitely appreciate the idea here. I see three alternatives to payloads:

1.) Prepackage all the sound files with the exploit.
2.) Download on demand.
3.) Leave it to the user (current approach).

The main issue with (1) is that you want *hax payloads to update when there are bugfixes, and there are many (version, new/old, region) instances to include. That doesn't make a lot of sense. (2) sounds a lot better, and in fact this is what hblauncher_loader by yellows8 does if necessary or the user requests it. But this increases complexity quite a bit, and leads to many failure modes. There's a size constraint on the shellcode included in the exploit, so another file would have to be included with additional code to load to add download support. This is a no-go, since it's already hard enough to get people to put `otherapp.bin` in the right place and just play the sound file. For these reasons I think the way it's done now is the right approach, and it's the one taken in most other homebrew exploits.

If you disagree with my reasoning here, feel free to reopen the issue or submit a PR addressing it, and I'd be happy to take another look.
